version: '2.3'
services:
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=password
    volumes:
      - 'redis-data:/bitnami'
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  redis-data: